<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1530866388113" stop="1530866388158">
  <name>test_001</name>
  <labels/>
  <test-cases>
    <test-case start="1530866388113" status="failed" stop="1530866388158">
      <name>Test_001.test_001_1</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>self = &lt;test_001.Test_001 object at 0x049EB230&gt;

    def test_001_1(self):
&gt;       assert 0
E       assert 0

Scripts\test_001.py:3: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="19076-MainThread"/>
        <label name="host" value="LAPTOP-G1U9NA19"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
